// Generated by gencpp from file subscriber/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SUBSCRIBER_MESSAGE_ADDTWOINTS_H
#define SUBSCRIBER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <subscriber/AddTwoIntsRequest.h>
#include <subscriber/AddTwoIntsResponse.h>


namespace subscriber
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace subscriber


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subscriber::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::subscriber::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::subscriber::AddTwoInts > {
  static const char* value()
  {
    return "subscriber/AddTwoInts";
  }

  static const char* value(const ::subscriber::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::subscriber::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::subscriber::AddTwoInts > 
template<>
struct MD5Sum< ::subscriber::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subscriber::AddTwoInts >::value();
  }
  static const char* value(const ::subscriber::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subscriber::AddTwoIntsRequest> should match 
// service_traits::DataType< ::subscriber::AddTwoInts > 
template<>
struct DataType< ::subscriber::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::subscriber::AddTwoInts >::value();
  }
  static const char* value(const ::subscriber::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subscriber::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::subscriber::AddTwoInts > 
template<>
struct MD5Sum< ::subscriber::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subscriber::AddTwoInts >::value();
  }
  static const char* value(const ::subscriber::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subscriber::AddTwoIntsResponse> should match 
// service_traits::DataType< ::subscriber::AddTwoInts > 
template<>
struct DataType< ::subscriber::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::subscriber::AddTwoInts >::value();
  }
  static const char* value(const ::subscriber::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBSCRIBER_MESSAGE_ADDTWOINTS_H
